## Запусти код ниже, чтобы установить NumPy

In [ ]:
%pip install numpy
import numpy as np
print(np.__version__)


## 1. Введение в массивы NumPy

**NumPy** — библиотека Python для работы с массивами (одномерные и многомерные структуры данных), быстрыми математическими и логическими операциями.

### Ключевой объект: `ndarray`
- Массивы одного типа данных
- Могут быть многомерными
- Поддерживают массовые операции, арифметику и сравнения

### Свойства одномерного массива NumPy:
- `shape`: форма (размерность по осям)
- `dtype`: тип данных
- `ndim`: число осей (измерений)


In [ ]:
import numpy as np

# Создание одномерного массива
arr = np.array([3, 7, 2, 5, 9, 12, 0, 1, -3, 8])

# Вывод массива и его свойств
print("Сам массив:", arr)
print("shape:", arr.shape)
print("dtype:", arr.dtype)
print("ndim:", arr.ndim)


## Генераторы массивов NumPy: arange() и reshape()

### np.arange()

`np.arange(start, stop, step)` создаёт одномерный массив чисел от `start` до `stop` (не включая `stop`), с заданным шагом `step` (по умолчанию 1).

- `np.arange(5)` → [0, 1, 2, 3, 4]
- `np.arange(2, 10, 2)` → [2, 4, 6, 8]

### reshape()

Массивы, созданные через `np.arange()`, по умолчанию одномерные. Чтобы сделать из них матрицу (или массив любой формы), применяют `.reshape(rows, columns)` или `.reshape(шаги по другим осям)`.

- `np.arange(12).reshape(3, 4)` → матрица 3 строки × 4 столбца:

    ```
    [[ 0,  1,  2,  3],
     [ 4,  5,  6,  7],
     [ 8,  9, 10, 11]]
    ```

**Важно:** Общее число элементов в reshape должно совпадать с длиной исходного массива!

---

In [ ]:
import numpy as np

# Обычный диапазон
arr = np.arange(10)
print("Массив от 0 до 9:", arr)

# Диапазон с произвольным шагом
arr2 = np.arange(2, 11, 2)
print("Чётные числа с 2 до 10:", arr2)

# Одномерный массив превращаем в матрицу 4x3
mat = np.arange(12).reshape(4, 3)
print("Матрица 4x3:\n", mat)


## Практическое задание: arange и reshape

1. Создайте массив из чисел от 100 до 109 включительно.
2. Преобразуйте его в матрицу 2x5 с помощью `.reshape()`.
3. Создайте массив нечётных чисел от 1 до 19 и сделайте из него массив из 2 строк.

---

Используйте `arange` + `reshape` для генерации предсказуемых массивов удобной формы.


In [ ]:
matrix = np.arange(100, 109+1).reshape(2, 5)
print(matrix)
matrix = np.arange(1, 19+1, 2)
matrix = matrix.reshape(2, len(matrix)//2)
print(matrix)

## Другие генераторы в NumPy

Кроме `np.arange()`, в NumPy есть другие функции для генерации массивов:

- `np.zeros(shape)` — создаёт массив из нулей с заданной формой
- `np.ones(shape)` — создаёт массив из единиц
- `np.full(shape, fill_value)` — массив, заполненный указанным значением
- `np.eye(N)` — единичная матрица размера N x N (главная диагональ — 1, остальные — 0)
- `np.linspace(start, stop, num)` — равномерно делит отрезок на num точек (подходит для вещественных чисел)
- `np.random.randint(low, high, size)` — массив случайных целых чисел в диапазоне [low, high)
- `np.random.rand(rows, columns)` — массив случайных float от 0 до 1


In [ ]:
import numpy as np

print("Массив нулей:\n", np.zeros((3, 4)))
print("Массив единиц:\n", np.ones((2, 5)))
print("Массив, заполненный 7:\n", np.full((3, 3), 7))
print("Единичная матрица:\n", np.eye(4))
print("10 точек между 0 и 1:\n", np.linspace(0, 1, 10))
print("Случайные целые числа 3x3:\n", np.random.randint(1, 10, (3, 3)))
print("Случайные числа от 0 до 1, форма 2x3:\n", np.random.rand(2, 3))


## Практическое задание: генераторы массивов

1. Создайте матрицу 3x4, заполненную только двойками.
2. Создайте единичную матрицу 5x5.
3. Сгенерируйте массив из 8 равномерно распределённых точек от 0 до 2 включительно.
4. Получите случайную матрицу 4x4 из целых чисел от 10 до 99.

---

Используйте эти генераторы для быстрых экспериментов и инициализации любых массивов!


In [ ]:
print(f'''{np.full((3, 4), 2)} \n
{np.ones((5,5))} \n
{np.linspace(0,2,8)}\n
{np.random.randint(10, 99, (4,4))}
      ''')

## 2. Индексация и срезы в массивах NumPy

NumPy позволяет удобно работать с массивами любых размерностей. Основные операции — это взятие элементов (индексация) и выделение диапазонов (срезы).

### Индексация одномерного массива

- `arr[i]` — обращение к элементу с индексом `i`, отсчёт ведётся с нуля.

### Индексация двумерного массива (матрицы)

- `arr[i, j]` — элемент в строке `i`, столбце `j`.
- Можно также обращаться к строке или столбцу целиком:
  - Строка: `arr[i]` или `arr[i, :]`
  - Столбец: `arr[:, j]`

### Срезы одномерного массива

- `arr[start:stop]` — подмассив с элементов от `start` до `stop` (не включая `stop`).
- Примеры:
  - `arr[2:5]` — элементы с 2-го по 4-й индекс

### Срезы двумерного массива

- `arr[start1:stop1, start2:stop2]` — "выделить прямоугольник" внутри матрицы
- `:` — означает взять все элементы вдоль соответствующей оси

Примеры работы с срезами:
- Верхний левый угол 2x2: `arr[0:2, 0:2]`
- Нижний правый угол 2x2: `arr[2:4, 2:4]`

---

### Дополнительные возможности:

- Можно делать сложные срезы, например, брать через шаг: `arr[::2, ::2]`
- Можно использовать отрицательные индексы: `arr[-1]` — последний элемент
- Для двумерного массива:  
  - `arr[:, 1:3]` — взять все строки, но только 2-й и 3-й столбцы

## Особенности работы со срезами и отрицательными индексами в NumPy

В срезах вида `array[start:stop]` элементы выбираются от start до **stop (не включая stop)**  
— Если `start < stop`, берутся элементы справа налево  
— Если `start >= stop` (например, `-2:0`), срез вернёт ПУСТОЙ массив

**Важно!**  
- Отрицательные индексы считаются от конца массива:  
  `-1` — последний элемент, `-2` — предпоследний и так далее
- Если хотите получить последние две строки матрицы, используйте:  
  `matrix[-2:, :]`
- Такой срез берёт элементы начиная с позиции -2 и до конца (т.е. 2 последние строки)

### Пример правильного среза


In [ ]:
import numpy as np

matrix = np.arange(16).reshape(4, 4)
print("Исходная матрица:\n", matrix)

# Индексация
print("Элемент [2, 3]:", matrix[2, 3])
print("Вторая строка:", matrix[1])
print("Третий столбец:", matrix[:, 2])

# Срезы
print("Верхний левый угол 2x2:\n", matrix[0:2, 0:2])
print("Нижний правый угол 2x2:\n", matrix[2:4, 2:4])

# Срез всей второй и третьей строки
print("Вторая и третья строки:\n", matrix[1:3])

# Строка в обратном порядке
print("Первая строка в обратном порядке:", matrix[0][::-1])


## Как найти индекс элемента в массиве или матрице NumPy

В NumPy для поиска позиции (индекса) конкретного значения используют функцию `np.where()`.

- Для одномерного массива:  
  `np.where(arr == значение)` — вернёт массив индексов, где найдено совпадение

- Для двумерного массива (матрицы):  
  `np.where(matrix == значение)` — вернёт кортеж из двух массивов: индексы строк и столбцов


In [ ]:
matrix = np.arange(16).reshape(4, 4)

# Найти индексы элемента со значением 10
result = np.where(matrix == 10)
print("Строки:", result[0], "Столбцы:", result[1])

# Если нужно получить индексы как пары (строка, столбец) — применить zip:
for row, col in zip(result[0], result[1]):
    print("Индекс элемента 10: [", row, ",", col, "]")


## Практическое задание 2

1. Создайте двумерный массив 4x4 с числами от 0 до 15.
2. Используя индексацию и срезы:
    - Найдите элемент с индексом `[2, 3]`
    - Выведите вторую строку целиком
    - Выведите третий столбец целиком
    - Выведите нижний правый угол 2x2 всей матрицы
    - Выведите последние две строки матрицы
    - Выведите первую строку в обратном порядке

---

Дополнительно (по желанию):
- Используйте отрицательные индексы для взятия элементов
- Выведите только чётные столбцы матрицы


In [ ]:
matrix = np.arange(16).reshape(4, 4)

print(f'''{matrix}\n
Элемент с индексом [2, 3]: {matrix[2,3 ]}
Вторая строка: {matrix[1, :]}
Третий столбец: {matrix[:, 2]}
Нижний правый угол 2х2:\n {matrix[2:4, 2:4]}
Последние две строки матрицы:\n {matrix[-2:, :]}
Первая строка в обратном порядке: {(matrix[0, ::-1])}
''')


## 3. Арифметические операции и массовые вычисления с массивами NumPy

Одно из главных преимуществ NumPy — возможность выполнять арифметику и сравнения сразу со всеми элементами массива без циклов.

### Операции над массивами

- **Сложение, вычитание, умножение, деление:**  
  Операции применяются ко всем элементам сразу!
    - `arr + 10` — прибавит 10 к каждому элементу массива
    - `arr1 + arr2` — поэлементное сложение двух массивов одинаковой формы
    - `arr * 2`, `arr / 3` и т.д.

- **Операции между массивами разной формы:**  
  NumPy использует механизм "broadcasting" — если формы совместимы, массивы автоматически "растягиваются" до нужного размера.

### Встроенные функции

- `np.add(arr1, arr2)`, `np.subtract(arr1, arr2)`, `np.multiply(arr1, arr2)`, `np.divide(arr1, arr2)`

### Примеры использования:
- Преобразование всех значений массива за одну команду
- Быстрая обработка большого объёма чисел

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

# Арифметика с массивами
print("a + 2:", a + 2)           # [3 4 5 6]
print("a * 10:", a * 10)         # [10 20 30 40]
print("a + b:", a + b)           # [11 22 33 44]
print("b / a:", b / a)           # [10. 10. 10. 10.]


## Практическое задание 3

1. Создайте массив из 5 любых целых чисел.
2. Прибавьте к каждому элементу массива 100. Выведите результат.
3. Создайте второй массив той же длины, заполненный числами на ваш выбор.
4. Умножьте два массива поэлементно. Выведите результат.
5. Поделите элементы первого массива на второй — поэлементно. Что произойдёт, если во втором массиве есть ноль?

---

Дополнительно:
- Используйте функцию `np.add()` для сложения массивов.
- Используйте функцию `np.multiply()` для поэлементного умножения.


In [ ]:
matrix1 = np.random.randint(0,10, (5))
matrix2 = np.random.randint(0,10, (5))
print(f'''1) Массив из 5 чисел: \n{matrix1}\n
2) Элементы увеличены на 100: \n{matrix1 +100}\n
3) Второй массив такого же размера:\n{matrix2}\n
4) Поэлементное умножение массивов:\n{matrix1*matrix2}\n
5) Поэлементное деление массивов:\n{matrix1/matrix2}\n
''')

## 4. Булевы массивы и фильтрация в NumPy

**Булевы массивы** — это массивы, содержащие только значения `True` и `False`.  
Они создаются автоматически, если сравнивать NumPy-массив с числом или другим массивом.

### Как работают булевы массивы и фильтрация:

- `arr > 5` — результат будет массив True/False, где True там, где элемент больше 5.
- Можно использовать такую маску для выбора элементов: `arr[arr > 5]`  
Получаются только те элементы, где условие выполнено.

### np.where — поиск индексов

- `np.where(arr > 5)` — возвращает индексы элементов, которые удовлетворяют условию.

### Комбинирование условий

- Можно совмещать условия: `(arr > 4) & (arr < 9)`  
Ampersand (`&`) используется вместо обычного "и" для массивов.

---

## Пример на практике



In [ ]:
import numpy as np

arr = np.array([1, 4, 7, 2, 10, 3, 5, 8])

# Создание маски — булевого массива
mask = arr > 5
print("Маска (arr > 5):", mask)                 # [False False True False True False False True]

# Фильтрация — выбор только элементов, где маска True
print("Элементы больше 5:", arr[mask])          # [ 7 10  8]

# Получение индексов, где условие выполнено
ind = np.where(arr > 5)
print("Индексы элементов > 5:", ind)            # (array([2, 4, 7]),)

# Однострочная фильтрация
print("Только > 5:", arr[arr > 5])              # [ 7 10  8]

# Пример с комбинированным условием
print("Элементы между 4 и 9:", arr[(arr > 4) & (arr < 9)])  # [7 5 8]



---

## Практическое задание

1. Создайте массив из 10 случайных целых чисел от 0 до 20.
2. Найдите все элементы, которые делятся на 3 без остатка.
3. Отобразите индексы этих элементов.
4. Выведите только чётные значения из массива.
5. Сколько элементов больше 10? Выведите это число.


In [ ]:
import numpy as np
matrix = np.random.randint(0, 20, (10))
print(f'''{matrix}
1) Массив из 10 случайных элементов от 0 до 20\n{matrix}\n
2) Все элементы, делящиеся на 3\n{matrix[matrix%3==0]}\n
3) Индексы этих элементов\n{np.where(matrix%3==0)[0]}\n
4) Чётные значения массива\n{matrix[matrix%2==0]}\n
5) Элементов больше 10: \n{matrix[matrix>10]}\n
Их количество: {len(matrix[matrix>10])}
''')

## 5. Математические функции и агрегирование в NumPy

NumPy умеет не только хранить наборы данных, но и быстро вычислять статистические и математические значения для целых массивов, строк/столбцов (агрегирование).

### Основные функции

- `np.sum(arr)` — сумма всех элементов массива
- `np.mean(arr)` — среднее арифметическое
- `np.max(arr)` — максимум
- `np.min(arr)` — минимум
- `np.std(arr)` — стандартное отклонение (разброс значений)
- `np.median(arr)` — медиана

### Вычисления по отдельным осям

Для двумерных массивов можно агрегировать по строкам (`axis=1`) или столбцам (`axis=0`):

- `np.sum(matrix, axis=0)` — сумма по столбцам
- `np.sum(matrix, axis=1)` — сумма по строкам

**axis=0** — по вертикали (столбцы).  
**axis=1** — по горизонтали (строки).

---



In [ ]:
import numpy as np

matrix = np.array([[1, 2, 7],
                   [3, 5, 8],
                   [4, 6, 9]])

# Сумма всех элементов
print("Сумма всех элементов:", np.sum(matrix))           # 45

# Среднее по всему массиву
print("Среднее значение:", np.mean(matrix))              # 5.0

# Макс и мин значения
print("Максимум в массиве:", np.max(matrix))             # 9
print("Минимум в массиве:", np.min(matrix))              # 1

# Сумма по столбцам
print("Сумма по столбцам:", np.sum(matrix, axis=0))      # [ 8 13 24]

# Сумма по строкам
print("Сумма по строкам:", np.sum(matrix, axis=1))       # [10 16 19]

# Стандартное отклонение
print("Ст. отклонение:", np.std(matrix))                 # 2.7386...

# Медиана
print("Медиана:", np.median(matrix))                     # 6.0


### Дополнительные полезные функции NumPy для анализа массивов

- `np.argmax(array)` — возвращает индекс (или индексы) максимального значения в массиве  
  (для двумерных: можно указать axis, чтобы получить по каждой строке или столбцу)
- `np.argmin(array)` — возвращает индекс минимального значения
- `np.argsort(array)` — возвращает индексы элементов, которые отсортируют массив по возрастанию
- `np.unique(array)` — возвращает отсортированный массив уникальных элементов
- `np.cumsum(array, axis=None)` — накопительная сумма (для оси или всего массива)
- `np.cumprod(array, axis=None)` — накопительное произведение
- `np.ptp(array)` — размах (разница между максимальным и минимальным элементом)
- `np.count_nonzero(array)` — считает количество ненулевых элементов (полезно для подсчёта того, сколько True в булевом массиве)
- `np.all(array, axis=None)` — True, если все элементы True (или не ноль)
- `np.any(array, axis=None)` — True, если хотя бы один элемент True (или не ноль)
- `array.flatten()` — превращает массив в одномерный (универсальный способ "сплющить" многомерный массив)
- `array.T` — транспонирование массива (поворот матрицы: строки становятся столбцами и наоборот)

**Пример для np.argmax() и np.argmin():**


In [ ]:
import numpy as np

arr = np.array([2, 8, 3, 7, 5])

print("Индекс максимума:", np.argmax(arr))  # 1 (8 — максимальный элемент)
print("Индекс минимума:", np.argmin(arr))  # 0 (2 — минимальный элемент)

matrix = np.array([[5, 12, 7],
                   [3, 18, 1]])

print("Максимум по строкам:", np.argmax(matrix, axis=1))  # [1 1] (по каждой строке)
print("Максимум по столбцам:", np.argmax(matrix, axis=0)) # [0 1 0]


---

## Практическое задание

1. Создайте случайную матрицу 3x5 с числами от 0 до 50.
2. Найдите сумму по каждой строке и по каждому столбцу.
3. Определите максимальное и минимальное значение во всей матрице.
4. Посчитайте среднее арифметическое по всей матрице.
5. Определите, в какой строке сумма самая большая.


In [ ]:
matrix = np.random.randint(0, 51, (3,5))
print(f'''1) \n{matrix}\n
2) Сумма:\n Столбцы:\n{np.sum(matrix, axis=0)}\n Строки: \n{np.sum(matrix, axis=1)}\n
3) Максимальное: \n{np.max(matrix)}\n Минимальное: \n{np.min(matrix)}\n
4) Среднее арифметическое \n{np.mean(matrix)}\n
5) Максимальная сумма: {np.max(np.sum(matrix, axis=1))} в строке №{np.argmax(np.sum(matrix, axis=1))+1}: \n{matrix[np.argmax(np.sum(matrix, axis=1))]}\n
''')

# NumPy: Работа с диагоналями

## 1. Главная диагональ

**Главная диагональ** — это элементы, у которых номер строки равен номеру столбца.

- Получить: `matrix.diagonal()`
- Сумма: `np.trace(matrix)`
- Производные диагонали: `matrix.diagonal(offset=k)` для смещений над/под главной

In [ ]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Главная диагональ
main_diag = matrix.diagonal()
print(main_diag)  # [1 5 9]

# Сумма главной диагонали
sum_main_diag = np.trace(matrix)
print(sum_main_diag)  # 15

# Диагональ выше главной (offset=1)
upper_diag = matrix.diagonal(offset=1)
print(upper_diag)  # [2 6]

# Диагональ ниже главной (offset=-1)
lower_diag = matrix.diagonal(offset=-1)
print(lower_diag)  # [4 8]


## 2. Побочная (контр-) диагональ

**Побочная диагональ** — это элементы, у которых сумма индексов равна размерности минус 1: \(i + j = n - 1\).

- Получить: индексация с помощью арифметики индексов: `matrix[np.arange(n), n-1-np.arange(n)]`
- Суммировать: применить `np.sum()` к полученной диагонали

In [ ]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

size = matrix.shape[0]
anti_diag = matrix[np.arange(size), size - 1 - np.arange(size)]
print(anti_diag)  # [3 5 7]

sum_anti_diag = np.sum(anti_diag)
print(sum_anti_diag)  # 15


## 3. Создание диагональных матриц

- Одномерный массив в диагональную матрицу: `np.diag(vector)`
- Для двумерной матрицы — извлечение диагонали: `np.diag(matrix)`

In [ ]:
import numpy as np

vector = np.array([10, 20, 30])
diag_matrix = np.diag(vector)
print(diag_matrix)
# [[10  0  0]
#  [ 0 20  0]
#  [ 0  0 30]]

# Получение главной диагонали из двумерной матрицы
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
main_diag_from_2d = np.diag(matrix)
print(main_diag_from_2d)  # [1 5 9]


## 4. Диагонали с произвольным смещением

- Выше главной диагонали: положительный offset
- Ниже главной диагонали: отрицательный offset
- Получить: `matrix.diagonal(offset=k)`, где `k` — смещение

In [ ]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Диагональ выше главной
upper_diag = matrix.diagonal(offset=1)
print(upper_diag)  # [2 6]

# Диагональ ниже главной
lower_diag = matrix.diagonal(offset=-1)
print(lower_diag)  # [4 8]


## 5. Суммирование и анализ диагоналей

- Применять к диагоналям стандартные NumPy-функции (`sum`, `mean`, и др.).
- Для побочных и любых диагоналей можно получить массив элементов и сразу к нему применить аналитические методы.

In [ ]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Главная диагональ
main_diag = matrix.diagonal()
mean_main_diag = np.mean(main_diag)
print(mean_main_diag)  # Среднее значение главной диагонали

# Побочная диагональ
size = matrix.shape[0]
anti_diag = matrix[np.arange(size), size - 1 - np.arange(size)]
std_anti_diag = np.std(anti_diag)
print(std_anti_diag)  # Стандартное отклонение побочной диагонали


## 6. Изменение элементов по диагоналям

- Для главной диагонали используйте `np.fill_diagonal()` или прямую индексацию.
- Для побочной диагонали — индексируйте вручную и присваивайте значения.
- Можно задавать любые значения, включая одинаковые или производные от позиции.

In [ ]:
import numpy as np

matrix = np.zeros((4, 4))

# Заполнение главной диагонали значением 5
np.fill_diagonal(matrix, 5)
print(matrix)
# [[5. 0. 0. 0.]
#  [0. 5. 0. 0.]
#  [0. 0. 5. 0.]
#  [0. 0. 0. 5.]]

# Изменение главной диагонали вручную
matrix[np.arange(4), np.arange(4)] = [10, 20, 30, 40]
print(matrix)
# [[10.  0.  0.  0.]
#  [ 0. 20.  0.  0.]
#  [ 0.  0. 30.  0.]
#  [ 0.  0.  0. 40.]]

# Изменение побочной диагонали
size = matrix.shape[0]
matrix[np.arange(size), size - 1 - np.arange(size)] = [1, 2, 3, 4]
print(matrix)
# [[10.  0.  0.  1.]
#  [ 0. 20.  2.  0.]
#  [ 0.  3. 30.  0.]
#  [ 4.  0.  0. 40.]]


## Теория: Побочная диагональ и её параллели в NumPy

- **Побочная диагональ** квадратной матрицы — это элементы с индексами (i, N-1-i), где N — размер стороны.
- В NumPy отсутствует прямой параметр offset для побочной диагонали, но можно использовать отражение по вертикали с помощью `np.fliplr(matrix)`, а затем работать с `.diagonal(offset)` так же, как для главной диагонали.
- В отражённой матрице главная диагональ соответствует побочной исходной, а offset позволяет получать параллельные диагонали по аналогии.

**Схема:**
| Оригинальная | Отражённая (`np.fliplr`) |
|---------------|--------------------------|
| Побочная      | Главная                  |
| Параллельные  | Параллельные главной     |

---


In [ ]:
import numpy as np

# Пример квадратной матрицы 5x5
matrix = np.arange(1, 26).reshape(5, 5)

# Отражение по вертикали
flipped = np.fliplr(matrix)

# Побочная диагональ (offset=0)
secondary_diag = flipped.diagonal()

# Диагональ левее побочной (offset=1)
upper_secondary_diag = flipped.diagonal(offset=1)

# Диагональ правее побочной (offset=-1)
lower_secondary_diag = flipped.diagonal(offset=-1)

print("Исходная матрица:\n", matrix)
print("Побочная диагональ:", secondary_diag)
print("Диагональ левее побочной:", upper_secondary_diag)
print("Диагональ правее побочной:", lower_secondary_diag)